// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gqWf3xNmlN_ycriB6nQfktZUp55yk44',
    appId: '1:959101581740:web:ad6b08336889e8189e2209',
    messagingSenderId: '959101581740',
    projectId: 'wails-ecommerce-app',
    authDomain: 'wails-ecommerce-app.firebaseapp.com',
    storageBucket: 'wails-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiPLFgA-7PvmKjt8ZE8RboNS0kzFnF8o',
    appId: '1:959101581740:android:4a5beb1335d11a469e2209',
    messagingSenderId: '959101581740',
    projectId: 'wails-ecommerce-app',
    storageBucket: 'wails-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoJrMaM5UtTX-KbTU4SkDppnqLaoVaDZU',
    appId: '1:959101581740:ios:17bfb0581b984f859e2209',
    messagingSenderId: '959101581740',
    projectId: 'wails-ecommerce-app',
    storageBucket: 'wails-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoJrMaM5UtTX-KbTU4SkDppnqLaoVaDZU',
    appId: '1:959101581740:ios:17bfb0581b984f859e2209',
    messagingSenderId: '959101581740',
    projectId: 'wails-ecommerce-app',
    storageBucket: 'wails-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0gqWf3xNmlN_ycriB6nQfktZUp55yk44',
    appId: '1:959101581740:web:811aed35614d77c49e2209',
    messagingSenderId: '959101581740',
    projectId: 'wails-ecommerce-app',
    authDomain: 'wails-ecommerce-app.firebaseapp.com',
    storageBucket: 'wails-ecommerce-app.appspot.com',
  );
}
